Task/1/schedule form
callmemars1/suai-bot-student-telegram-client pull request #3
Opened 2022-05-01 23:23 UTC by KuranovaPolina

1 task done

2022-05-02 11:49 UTC, callmemars1 requested changes
Не совсем понимаю зачем на боте какие-то бд и админки. Много лишнего.
Часть папок содержит просто пустые файлы, их тоже надо убрать.
Надо еще будет протестировать бота, посмотреть как он выводит.
@LomasovEgor, проверь код, я основные моменты ток чекал

2022-05-02 11:49 UTC, callmemars1 commented on .env.dist
> +# need to rename file and put correctly data
Я так понимаю это файл с примером. Тогда зачем он в репозитории

2022-05-02 11:49 UTC, callmemars1 commented on bot.py
> +from aiogram.contrib.fsm_storage.redis import RedisStorage2
Зачем здесь редис?

2022-05-02 11:49 UTC, callmemars1 commented on tg_bot/handlers/echo.py
> +from aiogram import types, Dispatcher
Эхо в боте зачем

2022-05-02 11:49 UTC, callmemars1 commented on tg_bot/handlers/schedule.py
> +async def schedule_schedule(message: Message):
Переименуй, непонятно что делает функция

2022-05-02 20:25 UTC, LomasovEgor requested changes

2022-05-02 20:25 UTC, LomasovEgor commented on tg_bot/creating_formatted_text.py
> +    for i in test_schedule_data["lessons"]:
Переменную в for`е лучше так не называй, а то то потом в теле цикла непонятно чо куда.
Вот тут например вместо i лучше написать lesson.  for lesson in test_schedule_data['lessons']

2022-05-02 20:25 UTC, LomasovEgor commented on tg_bot/creating_formatted_text.py
> +    for i in test_schedule_data["lessons"]:
То что schedule лучше в timetable переименовать, чтобы у всех одинаково было, обсуждали уже

2022-05-02 20:25 UTC, LomasovEgor commented on tg_bot/handlers/schedule.py
> +    await call.message.edit_reply_markup(reply_markup=days_scroll)
Функции  previous_day, next_day,  change_week в класс отдельный класс вынести в котором ты подобные функции прописываешь

2022-05-02 20:25 UTC, LomasovEgor commented on tg_bot/handlers/schedule.py
> +    dp.register_callback_query_handler(previous_day, text=["pr_day"])
Ну и функции регистрации  (register_pr_day, register_next_day, register_change_week) тоже в класс отдельный

2022-05-02 20:25 UTC, LomasovEgor commented on tg_bot/creating_formatted_text.py
> +    return result
В питончике еще принято в конце всех файлов пустую строчку оставлять. Можешь просто периодически Ctrl+Alt+L нажимать и пайчарм все сам красиво сделает.

2022-05-02 20:25 UTC, LomasovEgor commented on tg_bot/creating_formatted_text.py
> +def schedule_text(week_type, week_day):
Функции лучше глаголами называть, а то у тебя тут будто это переменная

2022-05-02 20:25 UTC, LomasovEgor commented on bot.py
> +from aiogram.contrib.fsm_storage.redis import RedisStorage2
По приколу

2022-05-02 20:25 UTC, LomasovEgor commented on bot.py
> +from aiogram.contrib.fsm_storage.redis import RedisStorage2
Я не знаю кто такой редис, но его ботяра как хранилище использует

2022-05-02 20:25 UTC, LomasovEgor commented on bot.py
> +from aiogram.contrib.fsm_storage.redis import RedisStorage2
И вообще я не понимаю я это Сереже пишу в итоге или нет ахвпхавх. Сережа если ты это видешб мяукни в ответ

2022-05-02 20:25 UTC, LomasovEgor commented on tg_bot/handlers/schedule.py
> +async def schedule_schedule(message: Message):
++

2022-05-02 20:25 UTC, LomasovEgor commented on bot.py
> +from tg_bot.handlers.schedule import register_schedule, register_pr_day, register_next_day, register_change_week
Я там ниже писал, что нужно функции в класс занести. Вот тут просто его импортируешь его и кайфуешь. И не придется каждый раз тут новую функцию импортировать.

2022-05-02 20:25 UTC, LomasovEgor commented on bot.py
> +    register_change_week(dp)
Ну и тут соответственно через класс просто все делаешь.

2022-05-02 20:25 UTC, LomasovEgor commented on tg_bot/creating_formatted_text.py
> +def schedule_text(week_type, week_day):
Еще, по возможности, лучше писать тип возвращаемого значения у функций и тип данных у переменных.
def schedule_text(week_type: тип данных, week_day: тип данных) -> тип возвращаемого значения:
Это необязательно, но когда неочевидно лучше писать. Потом когда функцию вызываешь редактор будет показывать чо куда вводить и ругаться если другой тип дал.

2022-05-02 20:27 UTC, callmemars1 commented on bot.py
> +from aiogram.contrib.fsm_storage.redis import RedisStorage2
мяу, редис - это бд для кэшировани ваще.

2022-05-02 20:28 UTC, LomasovEgor commented on bot.py
> +from aiogram.contrib.fsm_storage.redis import RedisStorage2
пон

2022-05-02 20:44 UTC, KuranovaPolina commented on tg_bot/handlers/schedule.py
> +    await call.message.edit_reply_markup(reply_markup=days_scroll)
Зачем?

2022-05-02 20:44 UTC, KuranovaPolina commented on tg_bot/handlers/schedule.py
> +    dp.register_callback_query_handler(previous_day, text=["pr_day"])
И это тоже зачем?)

2022-05-02 20:46 UTC, KuranovaPolina commented on tg_bot/creating_formatted_text.py
> +    return result
Спасибо, а то меня вечно эти подчеркивания в конце раздражают)

2022-05-03 12:36 UTC, LomasovEgor commented on tg_bot/handlers/schedule.py
> +    dp.register_callback_query_handler(previous_day, text=["pr_day"])
Вот чтобы каждый раз когда новую функцию добавляешь тебе не пришлось потом в других файлах что-то дописывать. (вот как тут)
```python
from tg_bot.handlers.schedule import register_schedule, register_pr_day, register_next_day, register_change_week
```
Ты делаешь класс с этими функциями и импортируешь его.
```python
from tg_bot.handlers.schedule import *class_name*
```
и потом когда в бд загружаешь то тоже не вот так пишешь
```python
def register_all_handlers(dp):
    register_admin(dp)
    register_schedule(dp)
    register_pr_day(dp)
    register_next_day(dp)
    register_change_week(dp)
```
а создаешь метод в классе который регистрирует все. И когда будешь добавлять новый функционал или менять существующий тебе не нужно будет в разных файлах код дописывать, и все изменения будут в пределах одного класса.

2022-05-05 12:33 UTC, KuranovaPolina commented on tg_bot/handlers/schedule.py
> +    dp.register_callback_query_handler(previous_day, text=["pr_day"])
До сих пор не вижу смысла в классах, но создала функцию register_full_timetable вызывающую все "регистрации"

2022-05-05 15:02 UTC, callmemars1 requested changes

2022-05-05 15:02 UTC, callmemars1 commented on bot.py
> +from aiogram.contrib.fsm_storage.redis import RedisStorage2
И все таки, редис зачем?

2022-05-05 15:02 UTC, callmemars1 commented on requirements.txt
> +aioredis==2.0
Здесь тоже редис проставлен

2022-05-05 15:02 UTC, callmemars1 commented on tg_bot/config.py
> +class DbConfig:
бд

2022-05-05 15:02 UTC, callmemars1 commented on bot.py
> +    storage = RedisStorage2() if config.tg_bot.use_redis else MemoryStorage()
бд

2022-05-05 15:02 UTC, callmemars1 commented on tg_bot/config.py
> +    use_redis: bool
редис

2022-05-05 15:02 UTC, callmemars1 commented on tg_bot/config.py
> +            use_redis=env.bool("USE_REDIS"),
редис

2022-05-05 15:02 UTC, callmemars1 commented on tg_bot/config.py
> +        db=DbConfig(
бд

2022-05-05 15:02 UTC, callmemars1 commented on bot.py
> +    dp = Dispatcher(bot, storage=storage)
Из конструктора storage можно убрать

2022-05-05 15:02 UTC, callmemars1 commented on bot.py
> +        await dp.storage.close()
Тк нет бд, то и нет необходимости ее закрывать

2022-05-05 15:02 UTC, callmemars1 commented on tg_bot/handlers/timetable.py
> +class Day:
### Это нельзя делать статиками!!!
Что будет если два пользователя захотят одновременно получить расписание на разные дни / типы недель

2022-05-05 15:02 UTC, callmemars1 commented on tg_bot/config.py
> +            admin_ids=list(map(int, env.list("ADMINS"))),
Админов мы убрали
Бтв то, что у тебя там заигнорено, перестанет работать

2022-05-05 15:02 UTC, callmemars1 commented on tg_bot/handlers/timetable.py
> +def register_pr_day(dp: Dispatcher):
Замени pr на previous или prev для читаемости

2022-05-05 15:14 UTC, KuranovaPolina commented on tg_bot/config.py
> +class DbConfig:
хм... самое интересное, что я убрала от сюда уже бд...

2022-05-05 15:14 UTC, KuranovaPolina commented on bot.py
> +    storage = RedisStorage2() if config.tg_bot.use_redis else MemoryStorage()
И от сюда

2022-05-05 15:19 UTC, KuranovaPolina commented on tg_bot/config.py
> +            admin_ids=list(map(int, env.list("ADMINS"))),
хм.. а если мы будем дальше развивать бота и нам надо будет что-то только для админов проверять?

2022-05-05 15:28 UTC, KuranovaPolina commented on tg_bot/handlers/timetable.py
> +class Day:
Это получается для каждого пользователя надо создавать отдельный объект класса Day?

2022-05-05 16:17 UTC, callmemars1 commented on tg_bot/handlers/timetable.py
> +class Day:
да

2022-05-05 16:18 UTC, callmemars1 commented on tg_bot/config.py
> +            admin_ids=list(map(int, env.list("ADMINS"))),
Тогда мы это добавим, но пока этого в планах нет

2022-05-05 16:40 UTC, LomasovEgor requested changes

2022-05-05 16:40 UTC, LomasovEgor commented on tg_bot/creating_formatted_text.py
> +def schedule_text(week_type, week_day):
Функции глаголами называть надо

2022-05-05 16:40 UTC, LomasovEgor commented on tg_bot/creating_formatted_text.py
> +    for i in test_schedule_data["lessons"]:
Переменную в for`е лучше так не называй, а то то потом в теле цикла непонятно чо куда.
Вот тут например вместо i лучше написать lesson. for lesson in test_schedule_data['lessons']

2022-05-07 09:10 UTC, callmemars1 reviewed
Ладно, пока пускай будет это, фиксить будем в следующих тасках
@LomasovEgor, посмотри и апрувни если тебя всё устроит

2022-05-07 09:12 UTC, callmemars1 approved these changes

2022-05-09 11:06 UTC, LomasovEgor approved these changes

2022-05-09 11:23 UTC, merged