Task/2/teachers form
callmemars1/suai-bot-student-telegram-client pull request #6
Opened 2022-05-17 20:41 UTC by KuranovaPolina

Added teacher info form without database

2022-05-22 16:50 UTC, callmemars1 requested changes

2022-05-22 16:50 UTC, callmemars1 commented on tg_bot/handlers/teacher_info.py
> +async def ask_teacher(message: Message):
По названию функции кажется, будто мы о чем то спрашиваем учителя. Переименуй на что-то более подходящее

2022-05-22 16:50 UTC, callmemars1 commented on tg_bot/handlers/teacher_info.py
> +async def display_teachers(message: Message, state: FSMContext):
Вынеси функции, отвечающий информацию о преподавателях в отдельный класс

2022-05-22 16:50 UTC, callmemars1 commented on tg_bot/handlers/teacher_info.py
> +def register_display_teachers(dp: Dispatcher):
Регистрацию хендлеров тоже

2022-05-28 09:02 UTC, callmemars1 requested changes

2022-05-28 09:02 UTC, callmemars1 commented on bot.py
> +from TimetableServiceHandlersRegistrator import TimetableServiceHandlersRegistrator
Вот здесь тогда тоже на регистрар поменяй

2022-05-28 14:45 UTC, callmemars1 requested changes

2022-05-28 14:45 UTC, callmemars1 commented on bot.py
> +from service_handlers_registrars.timetable_service_handlers_registrar import TimetableServiceHandlersRegistrator
Сам класс переименуй тоже

2022-05-29 12:16 UTC, callmemars1 approved these changes

2022-05-31 11:29 UTC, LomasovEgor approved these changes

2022-05-31 15:12 UTC, merged